config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#index'
  resources :games

  get 'games/:id/:game_piece_id/:x/:y', to: 'games#select', as: 'select'
  post 'games/:id/:game_piece_id/:new_x/:new_y', to: 'games#move', as: 'move'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_pieces, dependent: :destroy
  belongs_to :player_white, :class_name => "User", :foreign_key => "player_white_id"
  belongs_to :player_black, :class_name => "User", :foreign_key => "player_black_id"

  # Checks for last updated piece
  def last_piece
    self.game_pieces.order(:updated_at).last
  end

  # User a player of this game?
  def check_users(current_user)
    [self.player_white, self.player_black].include? current_user
  end

  # Player owns piece being moved?
  def check_player(gamepiece, current_user, new_x, new_y)
    gamepiece.user_id == current_user.id && self.player_move(gamepiece, new_x, new_y)
  end

  # Establishes first move (player white), & which player's move
  def player_move(gamepiece, new_x, new_y)
    false
    last_moved = self.last_piece
    if last_moved.moved == 0 && last_moved.user_id != self.player_white_id && self.player_white_id == gamepiece.user_id
      !self.is_obstructed?(gamepiece, new_x, new_y)
    elsif last_moved.moved > 0 && last_moved.user_id != gamepiece.user_id
      !self.is_obstructed?(gamepiece, new_x, new_y)
    else
      false
    end
  end

  def populate_pieces!
    if (self.game_pieces.where(game_id: self.id).take.nil?)
      game_piece_rank = ["Rook", "Knight", "Bishop", "Queen", "King", "Bishop", "Knight", "Rook"]
      (0..7).each do |i|
        game_pieces << (game_piece_rank[i].constantize).new(x: i, y: 0, game_id: self.id, user_id: player_white_id)  #player 1
        game_pieces << Pawn.new(x: i, y: 1, game_id: self.id, user_id: player_white_id)  #player 1
        game_pieces << (game_piece_rank[i].constantize).new(x: i, y: 7, game_id: self.id, user_id: player_black_id)  #player 2
        game_pieces << Pawn.new(x: i, y: 6, game_id: self.id, user_id: player_black_id)  #player 2
      end
    end
  end

  # return the player object of the other player
  def get_enemy_of(player_id)
    if !(player_white_id == player_id)
      return player_white_id
    else
      return player_black_id
    end
  end

  def get_enemy_king(player_id)
    # get enemy player...
    enemy = get_enemy_of(player_id)
    # get king position of player_id's king
    return (self.game_pieces.where("type = ? AND user_id=?", 'King', enemy)).first
  end

  # return true if player can attack new_x, new_x
  def can_attack?(player, new_x, new_y)
    # get all of the pieces alive for this player in this game
    opponents = self.game_pieces.where(:user_id => player, :alive => true)

    # iterate over each piece
    opponents.each do |opponent_piece|
      # check if the piece can move to new_x, new_y
      if opponent_piece.valid_move?(new_x, new_y) && !self.is_obstructed?(opponent_piece, new_x, new_y)
        return true
      end
    end
    return false
  end

  def capture_move?(game_piece, new_x, new_y)
    if game_piece.type == "Pawn" && game_piece.can_passant_capture
      captured_piece = self.game_pieces.order(:updated_at).last
    else
      #define the captured piece on new position
      captured_piece = self.game_pieces.where(:x => new_x, :y => new_y).first
    end
    #get enemy's user id
    # NOTE: This did not work; commented it out & repaired functionality [S.E.]
    # enemy_id = get_enemy_of(game_piece.id)
    if captured_piece && captured_piece.user_id != game_piece.user_id # enemy_id - Did not work for white taking black
      captured_piece.update_attributes(:x => nil, :y => nil, :alive => false)
      # p captured_piece
      return true
    end
    return false

  end

  # NOTE you could pass a king in here instead too...
  def in_check?(player_id)
    # get enemy king
    king = get_enemy_king(player_id)

    # call can_attack and return the right value
    return can_attack?(player_id, king.x, king.y)
  end

  def check_mate?(player_id)
    check_mate = false
    valid_indices = false
    king = get_enemy_king(player_id)
    x = king.x
    y = king.y
    #get enemy king's valid move locations
    total_indices = [[x-1,y+1], [x-1,y],[x-1,y-1], [x,y-1], [x+1,y-1], [x+1,y], [x+1,y+1], [x,y+1]]
    #call can_attack on each of the above positions
    total_indices.each do |i|
      if !(i[0] < 0) && !(i[0] > 7) && !(i[1] < 0) && !(i[1] > 7) && !self.is_obstructed?(king, i[0], i[1])
        valid_indices = true
        if king.valid_move?(i[0], i[1]) 
          if !can_attack?(player_id, i[0], i[1])
            return false
          end
        end
      end
    end
    if valid_indices
      return true
    end
  end

  
  def is_obstructed?(gamepiece, new_x, new_y)
    # from game_controller.rb, this should probably be called :
    # if !@game.is_obstructed?(@game_piece, @new_x, @new_y)
    #   @game_piece.move_piece(@new_x, @new_y) <- move only if it is NOT obstructed
    #
    current_x = gamepiece.x
    current_y = gamepiece.y
    new_x = new_x.to_i
    new_y = new_y.to_i
    team_id = gamepiece.user_id

    # return true means there is obstruction in movement --> that means bad
    if is_occupied_by_teammate?(current_x, current_y, new_x, new_y, team_id, gamepiece.id)
      return true
    end

    if gamepiece.type == "Knight"
      return false
    end
    #assumption is that the piece won't move to the same place.
    #e.g., [2, 2] -> [2, 2]
    #that validation is done before reaching to is_obstructed? method

    #check if the move is horizontal
    if current_y == new_y
      if is_horizontal_ok?(current_x, current_y, new_x, new_y) == false
        return true
      end
    end

    #check if the move is vertical
    if current_x == new_x
      if is_vertical_ok?(current_x, current_y, new_x, new_y) == false
        return true
      end
    end

    #check if the move is diagonal
    if ((new_x - current_x).abs == (new_y - current_y).abs)
      if is_diagonal_ok?(current_x, current_y, new_x, new_y) == false
        return true
      end
    end

    return false

  end

  def is_occupied_by_teammate?(current_x, current_y, new_x, new_y, team_id, gamepiece_id)
    game_pieces.each do |game_piece|
      if (game_piece.x == new_x && game_piece.y == new_y && game_piece.user_id == team_id && game_piece.id != gamepiece_id)
        return true
      end
    end
    return false
  end

  def is_horizontal_ok?(current_x, current_y, new_x, new_y)
    x2 = new_x  # x2 value is larger than x1
    x1 = current_x
    if new_x < current_x
      x2 = current_x
      x1 = new_x
    end
    # create array of x.  If game_piece.x is the same as one of array of x,
    # there is an obstruction.
    # only need to check between x1 and x2 values; x1 and x2 are not included.
    # x1+1 to exclude x1 point.  Using ... to exclude x2
    x_array = ((x1+1)...x2).map {|i| i}
    game_pieces.each do |game_piece|
      if x_array.include?(game_piece.x) && game_piece.y == current_y
        return false  # false means horizontal_move is NOT ok
      end
    end
    return true
  end

  def is_vertical_ok?(current_x, current_y, new_x, new_y)
    y2 = new_y  # y2 value is larger than y1
    y1 = current_y
    if new_y < current_y
      y2 = current_y
      y1 = new_y
    end
    # create array of y.  If game_piece.y is the same as one of array of y,
    # there is an obstruction.
    y_array = ((y1+1)...y2).map {|i| i}
    game_pieces.each do |game_piece|
      if y_array.include?(game_piece.y) && game_piece.x == current_x
        return false  # false means horizontal_move is NOT ok
      end
    end
    return true
  end

  def is_diagonal_ok?(current_x, current_y, new_x, new_y)

    two_d_array = []

    if (new_y > current_y && new_x > current_x)  # piece moves to up right
      two_d_array = create_two_d_array_for_diagonal_check(current_x+1, current_y+1, current_y+1, new_y, 1, 1, two_d_array)

    elsif (new_y > current_y && new_x < current_x) # piece moves to up left
      two_d_array = create_two_d_array_for_diagonal_check(current_x-1, current_y+1, current_y+1, new_y, -1, 1, two_d_array)

    elsif (new_y < current_y && new_x > current_x) # piece moves to down right
      two_d_array = create_two_d_array_for_diagonal_check(current_x+1, current_y-1, current_x+1, new_x, 1, -1, two_d_array)

    else # new_y < current_y && new_x < current_x.  piece moves to down left
      two_d_array = create_two_d_array_for_diagonal_check(current_x-1, current_y-1, new_x, current_x-1, -1, -1, two_d_array)
    end

    # this loop checks all game_piece to see if there is an obstacle.
    found_match = false
    game_pieces.each do |game_piece|
      piece_ary = [game_piece.x, game_piece.y]
      two_d_array.each do |ary|
        if piece_ary == ary
          found_match = true
        end
      end
    end

    if found_match
      return false
    else
      return true
    end
  end

  def create_two_d_array_for_diagonal_check(x, y, loop_init, loop_end, x_incr, y_incr, two_d_array)
    # this create a two-dimensional array for all squares between current position and new_position.
    # current position and new position are excluded from the array.
    # for example, if the piece moves from [2, 1] to [5, 4], the array should contains
    # [[3, 2], [4, 3]].
    i = loop_init
    while i < loop_end
      two_d_array  << [x, y]
      x += x_incr
      y += y_incr
      i += 1
    end
    return two_d_array
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @game = Game.all
  end

  def show
    # Determine if the game is won
    @winner = nil
    @game = Game.find(params[:id])
    @users = User.all
    won = @game.won
    if won != nil
      @winner = @users.find(@game.won).email
    end
    
    @game_pieces = @game.game_pieces
    @resign_message = nil
    if @game.player_white_id == -1
      @resign_message = "Player Black Won! (Player White Has Left the Match)"
    elsif  @game.player_black_id == -1
      @resign_message = "Player White Won! (Player Black Has Left the Match)"
    end

  end

  def create
    @game = Game.create(game_params)
    redirect_to games_path
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(game_params)
    @game.populate_pieces!
    if @game.valid?
      @game_pieces = @game.game_pieces
      redirect_to game_path
    end
  end

  def select
    @game = Game.find(params[:id]) # blah blah blah
    @game_pieces = @game.game_pieces
    @game_piece = GamePiece.find(params[:game_piece_id])
  end

  def move
    @game = Game.find(params[:id])
    @game_pieces = @game.game_pieces
    @game_piece = GamePiece.find(params[:game_piece_id])
    # NOTE converting to integer here saves you from having to do it in every piece
    new_x = params[:new_x].to_i
    new_y = params[:new_y].to_i

    if @game.check_player(@game_piece, current_user, new_x, new_y) && @game_piece.valid_move?(new_x, new_y)
      #Capture piece if capture_move? return true
      if @game.capture_move?(@game_piece, new_x, new_y)
        move_save(new_x, new_y)
      end

      # TODO if the piece is a king, it cannot be moved into check
      if @game_piece.type == 'King'
        opponent = @game.get_enemy_of(@game_piece.user_id)
        if !@game.can_attack?(opponent, new_x, new_y)
          move_save(new_x, new_y)
        else
          flash[:notice] = "King cannot be moved in check position!"
        end
      elsif @game_piece.type == 'Pawn'
        # check if it reached y = 0 or y = 7
        if new_y==0 || new_y == 7
	        p "check if pawn reaches other end"
	        # then change the type to queen.
	        @game_piece.type = 'Queen'
	        @game_piece = @game_piece.becomes(@game_piece.type.constantize)
	      end
	      # call move and save
	      move_save(new_x, new_y)
      else
        move_save(new_x, new_y)
      end
    else
      # can't move there!
      flash[:notice] = "Invalid move"
    end
    base_uri = 'https://vivid-heat-2313.firebaseIO.com/'
    firebase = Firebase::Client.new(base_uri)
    response = firebase.set("#{@game.id}",  :created => Firebase::ServerValue::TIMESTAMP)
    # response.success? # => true

    redirect_to game_path
  end

  def destroy
    @game = Game.find(params[:id])
    @game_pieces = @game.game_pieces
    if @game.player_white == current_user
      @game.player_white_id = -1

      flash[:notice] = "Player Black Won!"
    else
      @game.player_black_id = -1
      flash[:notice] = "Player White Won!"
    end
    @game.destroy
    # to-do
    # need to add code here for a winning player
    # (points add?  number of winning game added for a winner?)
    redirect_to root_path
  end

  private

  def game_params
    params.require(:game).permit(:player_white_id, :player_black_id, :name_for_game)
  end

  def move_save(new_x, new_y)
    @game_piece.move_to(new_x, new_y)
    @game_piece.save

    if @game.check_mate?(@game_piece.user_id)
      flash[:error] = "checkmate"
      @winner = (@game.player_black == current_user)? @game.player_black : @game.player_white
      flash[:notice] = "Game Over"
      @game.save_winner(@winner.id)
    elsif @game.in_check?(@game_piece.user_id)
      flash[:error] = "check"
    end

  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="col-xs-10 col-xs-offset-1 booyah-box">

<div class="col-xs-5">
  <div>
    <h4>Games you are playing <span class="instruct">(click on game to resume)</span></h4>
    <% current_games = 0 %>
    <ol>
      <% @game.where("player_black_id = ? OR player_white_id = ?", "#{current_user.id}", "#{current_user.id}").find_each do |game| %>
        <% current_games = 1 %>
        <li class="game-list">
          <span class="game-link"><%= link_to "#{game.name_for_game}", game_path(game) %></span>
            <% if game.player_black_id == current_user.id %>
              <em>You're player black</em>
            <% elsif game.player_white_id == current_user.id && game.player_black_id != nil %>
              <em>You're player white</em>
            <% else %>
              <b>(waiting for an opponent)</b>
            <% end %>
            <% if game.last_piece && game.last_piece.user_id != current_user.id %>
              <b>&nbsp;&nbsp;[Your move]</b>
            <% end %>
          </span>
        </li>
      <% end %>
    </ol>
    <% if current_games == 0 %>
      <p>
        You don't have any games in progress, yet.
      </p>
    <% end %>
  </div>
  <br />

  <div>
    <h4>Start a new game?</h4>
    <%= simple_form_for Game.new, :url => games_path do |f| %>
      <%= f.input :player_white_id ,:as => :hidden, :input_html => { :value => current_user.id } %>
      <%= f.input :player_black_id ,:as => :hidden, :value => nil %>
      <div class="input-group">
        <%= f.input :name_for_game, :as => :hidden, :input_html => {:value => "#{current_user.email[/[^@]+/]}"} %>
        <span class="match-name"><%= "Player white: " %>
          <b><%= current_user.email[/[^@]+/] %></b></span>
        <span class="input-group-btn"><%= f.submit "Create game", :class => 'btn btn-warning' %></span>
      </div>
    <% end %>
  </div>
</div>

<div class="col-xs-5 col-xs-offset-1 vert-border">
  <h4>Pick an opponent &#38; join a game</h4>
  <% opponents_games = 0 %>
    <% @game.where(player_black_id: nil).where.not(player_white_id: current_user.id).find_each do |game| %>
      <% opponents_games += 1 %>
      <%= simple_form_for game do |f| %>
        <div class="input-group">
          <%= f.input :player_black_id ,:as => :hidden, :input_html => { :value => current_user.id } %>
          <%= f.input :name_for_game,:as => :hidden, :input_html => { :value => "#{game.name_for_game} vs #{current_user.email[/[^@]+/]}" } %>
          <span class="match-name"><%= "Game #{opponents_games} - Challenge player: " %>
            <b><%= game.name_for_game %></b></span>
          <span class="input-group-btn"><%= f.submit "Join this game", :class => 'btn btn-warning' %></span>
        </div>
      <% end %>
    <% end %>
    <% if opponents_games == 0 %>
      <p>
        No available games to join.
      </p>
    <% end %>
</div>

</div>

app/views/games/select.html.erb
<div id="board" class="col-xs-10 col-xs-offset-1">
  <% positions = {} %>

  <table>
    <% ('a'..'h').to_enum.with_index.reverse_each do |letter, index| %>
      <tr>
        <th>
          <%= letter %>
        </th>
        <% (0..7).each do |col| %>
          <td>
            <% if @game_piece.x == col && @game_piece.y == index %>
              <span class="selected icon">
                <%= @game_piece.icon %>
              </span>
            <% else %>
              <span class="center-text">
                <%= link_to 'next move', move_path(@game, :game_piece_id => @game_piece.id, :new_x => col, :new_y => index),:method => :post, :class => "move" %>
              </span>
              <% @game_pieces.each do |game_piece| %>
                <% if game_piece.x == col && game_piece.y == index %>
                  <% if @game.player_white_id == game_piece.user_id.to_i %>
                    <span class="icon white">
                  <% else %>
                    <span class="icon black">
                  <% end %>
                  <%= game_piece.icon %>
                  </span>
                <% end %>
              <% end %>

              <!--% row %-->
              <% col %>
            <% end%>
          </td>
        <% end %>
      </tr>
    <% end %>
    <tfoot>
      <tr>
        <% (0..8).each do |num| %>
          <th class="text-center foot">
            <%= num if num != 0 %>
          </th>
        <% end %>
      </tr>
    </tfoot>
  </table>
</div>

app/views/games/show.html.erb
<% if @game.check_users(current_user) %>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="https://cdn.firebase.com/js/client/2.4.0/firebase.js"></script>
  <style>
    .draggable.ui-draggable-dragging {color: gray;}
  </style>
  <div id="timestamp" data-time-stamp="<%= (Time.now.to_f * 1000).to_i %>"></div>
  <script>
    $( init );

    var piece_id, x_coord_new, y_coord_new;

    function init() {

      $('.draggable').draggable( {
        stop: handleDragEvent
      });
      $('.droppable td').droppable( {
        drop: handleDropEvent
      });
    }

    function handleDragEvent( event, ui ) {
      var draggable = ui.draggable;
      piece_id = $(this).attr("id");
      var game_id= '<%=@game.id%>';
      //console.log("game_id is " + game_id);
      //console.log("piece_id is " + piece_id);
      //console.log("event taget is is" + event.target.id)
      //console.log("x_coord_new is " + x_coord_new + " and y_coord_new is " + y_coord_new);
      var path = "/games/" + game_id + "/" + piece_id + "/" + x_coord_new + "/" + y_coord_new;

      $('#move').attr({
        'action': path
      });
      $('#move').submit();
      // get the destination coordinate
      //alert( 'Dragged!' +  "(ID = " + piece_id + ")");
    }

    function handleDropEvent( event, ui ) {
      var draggable = ui.draggable;
      var droppableID = $(this).attr("id");
      //console.log("droppable id is " + droppableID);
      // get the destination coordinate
      x_coord_new = droppableID.charAt(droppableID.length-2);
      y_coord_new = droppableID.charAt(droppableID.length-1);
      //alert( 'Dropped!' +  "(" + x_coord_new + ", " + y_coord_new + ")");
    }

    // firebase_path is hardcoded.  Firebase account is created and
    // https://vivid-heat-2313.firebaseio.com/ link is provided.
    // when a game piece moves, timestamp is created in database inside the link.
    // the idea is that to get this timestamp inside firebase and
    // compare the time when this show.html is refreshed and refresh
    // the browser if necessary.
    var firebase_path = 'https://vivid-heat-2313.firebaseio.com/' + '<%=@game.id%>' + "/";
    var myDataRef = new Firebase(firebase_path);
    // load current time (id = timestamp is defined on line 8)
    var load_time_stamp = $('#timestamp').data('time-stamp');
    //console.log("load_time_stamp is " + load_time_stamp);

    // the statement below grabs the timestamp "created" from firebase database.
    myDataRef.on('value', function(snapshot) {
      data = snapshot.val();
      var time_fb = data.created;
      //console.log("time_fb is " + time_fb);
      if (time_fb > load_time_stamp) {
        location.reload();
      }
    });

  </script>
  <div id="board" class="col-xs-10 col-md-7 col-xs-offset-1">
    <% if @resign_message != nil %>
      <h1><%= @resign_message %></h1>
      <h3><%= link_to 'Go back to Game Dashboard', games_path %></h3>
    <% end %>
    <div class="results">
      <%= form_tag '', :id => "move"%>
    </div>
    
    <div>
      <% if @winner != nil %>
       <%= link_to "#{@winner} WON!", game_path(@game), :method => :delete, :data => {:confirm => 'GAME OVER'}, :class => 'btn btn-primary' %>
      <% end %>
    </div>
    
    <table class="droppable">
      <% ('a'..'h').to_enum.with_index.reverse_each do |letter, index| %>
        <tr>
          <th>
            <%= letter %>
          </th>
          <% (0..7).each do |col| %>
            <% square_id = "square" + col.to_s + index.to_s %>
            <td id= "<%= square_id %>">
                <% @game_pieces.each do |game_piece| %>
                  <% if game_piece.x == col && game_piece.y == index %>
                    <% if @resign_message == nil %>
                      <% if @game.player_white_id == game_piece.user_id.to_i %>
                        <span class="icon white">
                      <% else %>
                        <span class="icon black">
                      <% end %>

                      <div class="draggable" id= "<%= game_piece.id %>">
                        <%= game_piece.icon %>
                      </div>
                      <% end %>
                      <!--%= link_to game_piece.icon, select_path(:game_piece_id => game_piece, :x => game_piece.x, :y => game_piece.y) %-->
                    </span>
                  <% end %>
                <% end %>
              <!--% row %-->
              <% col %>
            </td>
          <% end %>
        </tr>
      <% end %>
      <tfoot>
        <tr>
          <% (0..8).each do |num| %>
            <th class="text-center foot">
              <%= num if num != 0 %>
            </th>
          <% end %>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="col-xs-10 col-md-4">
    <div>
      <% if @resign_message == nil %>
        <%= link_to 'Resign', game_path(@game), :method => :delete, :data => {:confirm => 'Are you sure you want to resign this game?'}, :class => 'btn btn-primary' %>
      <% end %>
    </div>
    <div class="turn">
      <br />
      <% if @game.last_piece && @game.last_piece.user_id != @game.player_black_id %>
        <p><%= @game.player_black.email[/[^@]+/] %>: black move</p>
      <% else %>
        <p class="white-move"><%= @game.player_white.email[/[^@]+/] %>: white move</p>
      <% end %>
    </div>

  </div>


<% else %>
    <% flash[:alert] = "Access denied. This is not the game you are looking for." %>
<% end %>